TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += xrmSliceVersion.db
DB +=  xrmSliceAI_HT_128CH.db
DB +=  xrmSliceAI_HT_32CH.db
DB +=  xrmSliceAI_HT_16CH.db
DB +=  xrmSliceAI_PM_128CH.db
DB +=  xrmSliceAI_PM_32CH.db
DB +=  xrmSliceAI_PM_16CH.db
DB += xrmSliceSP_PM_8.db
DB += xrmSliceSP_HT_8.db

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

